name=UltrasonicX
version=1.0.1
author=M7MED (Mohamed Badawy)
maintainer=M7MED bdwym2007@gmail.com
sentence=Advanced Ultrasonic Sensor Library for HC-SR04
paragraph=Provides distance measurement, motion detection, averaging and speed calculation.
category=Sensors
url=https://github.com/M7MEDpro/UltrasonicX
architectures=*