name=UltrasonicX
version=1.0.1
author=M7MED (Mohamed Badawy)
maintainer=M7MED bdwym2007@gmail.com
sentence=Advanced Non-Blocking Ultrasonic Sensor Library for HC-SR04
paragraph=Provides non-blocking distance measurement (m, cm, mm, in, ft, yd), motion detection, averaging and speed calculation.
category=Sensors
url=https://github.com/M7MEDpro/UltrasonicX
architectures=*